version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
  backend:
    build: "./backend"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.example
    depends_on:
      - mongo
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data: